runtime: go
api_version: go1.8
threadsafe: true
module: default
instance_class: B1

basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /remindme
  script: _go_app
  login: admin
- url: /new
  script: _go_app

