runtime: go
api_version: go1.8
threadsafe: true
module: default
instance_class: F1

automatic_scaling:
  min_idle_instances: 0

handlers:
- url: /remindme
  script: _go_app
  login: admin
- url: /new
  script: _go_app

